# Generated by Django 6.0.1 on 2026-06-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="anomaly_threshold",
            field=models.IntegerField(
                default=100, help_text="Latencia en ms para marcar anomalia"
            ),
        ),
        migrations.AddField(
            model_name="router",
            name="ping_interval",
            field=models.IntegerField(
                default=5, help_text="Segundos entre pings (minimo 2)"
            ),
        ),
    ]
