# Generated by Django 6.0.1 on 2026-06-19 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_router_anomaly_threshold_router_ping_interval"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NetworkMetric",
        ),
    ]
