# Generated by Django 6.0.1 on 2026-06-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0004_delete_networkmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Grupo: Core, Sucursal, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="router",
            name="sla_pings",
            field=models.IntegerField(
                default=3,
                help_text="Pings consecutivos con latencia alta para alerta SLA",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="type",
            field=models.CharField(
                choices=[
                    ("down", "Caida"),
                    ("recovery", "Recuperacion"),
                    ("sla", "Alerta SLA"),
                    ("sla_ok", "SLA Recuperado"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="HourlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("avg_latency", models.FloatField(default=0)),
                ("max_latency", models.FloatField(default=0)),
                ("min_latency", models.FloatField(default=0)),
                ("packet_loss_pct", models.FloatField(default=0)),
                ("pings_total", models.IntegerField(default=0)),
                ("anomalies", models.IntegerField(default=0)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.router",
                    ),
                ),
            ],
            options={
                "ordering": ["-hour"],
                "unique_together": {("router", "hour")},
            },
        ),
    ]
