# Generated by Django 6.0.1 on 2026-06-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0005_router_group_router_sla_pings_alter_incident_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hourlystats",
            name="downtime_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
